[azure]
redirect_uri = "http://localhost:8501"
client_id = "SEU CLIENT ID"
client_secret = "SEU CLIENT SECRET"
tenant_id = "SEU TENANT ID"

[auth_config]
expiry_days = 1
key = 'teste_ad'
name = 'teste_ad'